name: chat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.12
  firebase_database: ^9.0.4
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  flutter_speed_dial: ^5.0.0+1
  #curved_navigation_bar: ^0.3.7
  avatar_glow: ^2.0.2
  flutter_svg: ^1.0.3
  glassmorphism: ^3.0.0
  flutter_rating_bar: ^4.0.0
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.13
  # simple_animations: ^1.3.3
  flutter_dropdown_alert: ^1.0.3
  # sffffff
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  google_sign_in: ^5.3.2
  firebase_messaging: ^11.4.1
  flutter_local_notifications: ^9.5.3
  provider: ^6.0.2  #^5.0.0
  uuid: ^3.0.6
  dio: ^4.0.0
  json_annotation: ^4.0.1
  google_fonts: ^2.1.0

  simple_animations: ^4.0.2
  flutter_svg_provider:
  font_awesome_flutter:
  flare_flutter:
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3
  build_runner: ^2.0.4
  
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/
      - assets/icon/
      - assets/img/
      - assets/slider/
      - assets/svg/
      - assets/images/

 